FROM eclipse-temurin:21-jre-alpine
LABEL maintainer="igna-alva-uni"
WORKDIR /app
COPY target/*.jar app.jar

ENV EUREKA_SERV=http://eureka-server:8761/eureka

EXPOSE 9000
ENTRYPOINT ["java", "-jar","app.jar"]