server:
  port: 9001
  forward-headers-strategy: framework
  error:
    include-stacktrace: never

spring:
  application:
    name: ms-usuarios

  kafka:
    bootstrap-servers: ${KAFKA_SERV:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "spring.json.add.type.headers": true
    consumer:
      group-id: consumers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "cl.duoc.*"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/torneos}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123}

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: users

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERV:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 60

springdoc:
  api-docs:
    path: /usuarios/v3/api-docs
  swagger-ui:
    path: /usuarios/swager
    disable-redirect: true
