server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      server:
        webflux:
          trusted-proxies: ".*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-usuarios
          uri: lb://MS-USUARIOS
          predicates:
            - Path=/api/v1/usuarios/**,/usuarios/swager/**,/usuarios/swagger-ui/**,/usuarios/v3/api-docs/**
        - id: ms-autenticaciones
          uri: lb://MS-AUTENTICACIONES
          predicates:
            - Path=/api/v1/autenticaciones/**,/autenticaciones/swager/**,/autenticaciones/swagger-ui/**,/autenticaciones/v3/api-docs/**
        - id: ms-juegos
          uri: lb://MS-JUEGOS
          predicates:
            - Path=/api/v1/juegos/**,/juegos/swager/**,/juegos/swagger-ui/**,/juegos/v3/api-docs/**
        - id: ms-torneos
          uri: lb://MS-TORNEOS
          predicates:
            - Path=/api/v1/torneos/**,/torneos/swager/**,/torneos/swagger-ui/**,/torneos/v3/api-docs/**
        - id: ms-equipos
          uri: lb://MS-EQUIPOS
          predicates:
            - Path=/api/v1/equipos/**,/equipos/swager/**,/equipos/swagger-ui/**,/equipos/v3/api-docs/**
        - id: ms-partidas
          uri: lb://MS-PARTIDAS
          predicates:
            - Path=/api/v1/partidas/**,/partidas/swager/**,/partidas/swagger-ui/**,/partidas/v3/api-docs/**
        - id: ms-inscripciones
          uri: lb://MS-INSCRIPCIONES
          predicates:
            - Path=/api/v1/inscripciones/**,/inscripciones/swager/**,/inscripciones/swagger-ui/**,/inscripciones/v3/api-docs/**
        - id: ms-ranking
          uri: lb://MS-RANKING
          predicates:
            - Path=/api/v1/ranking/**,/ranking/swager/**,/ranking/swagger-ui/**,/ranking/v3/api-docs/**
        - id: ms-notificaciones
          uri: lb://MS-NOTIFICACIONES
          predicates:
            - Path=/api/v1/notificaciones/**,/notificaciones/swager/**,/notificaciones/swagger-ui/**,/notificaciones/v3/api-docs/**
        - id: ms-estadisticas
          uri: lb://MS-ESTADISTICAS
          predicates:
            - Path=/api/v1/estadisticas/**,/estadisticas/swager/**,/estadisticas/swagger-ui/**,/estadisticas/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/estadisticas/(?<segment>.*), /api/v1/stats/${segment}
        - id: shared-auth
          uri: lb://MS-AUTENTICACIONES
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /api/v1/autenticaciones/${segment}

springdoc:
  swagger-ui:
    path: /ms/swagger
    urls:
      - name: Usuarios (ms-usuarios)
        url: /usuarios/v3/api-docs
      - name: Autenticaciones (ms-autenticaciones)
        url: /autenticaciones/v3/api-docs
      - name: Juegos (ms-juegos)
        url: /juegos/v3/api-docs
      - name: Torneos (ms-torneos)
        url: /torneos/v3/api-docs
      - name: Equipos (ms-equipos)
        url: /equipos/v3/api-docs
      - name: Partidas (ms-partidas)
        url: /partidas/v3/api-docs
      - name: Inscripciones (ms-inscripciones)
        url: /inscripciones/v3/api-docs
      - name: Ranking (ms-ranking)
        url: /ranking/v3/api-docs
      - name: Notificaciones (ms-notificaciones)
        url: /notificaciones/v3/api-docs
      - name: Estadisticas (ms-estadisticas)
        url: /estadisticas/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERV:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
